spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://${DB_URL:127.0.0.1}:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
server:
  port: 8082